### ISSUE TITLE
I can't build in android again

### ISSUE THREAD

**Issue by nyaruru1** [Bzi-Han/AndroidSurfaceImgui#10]
I patch 5 file but build error 
Log show clang16

**Comment by Bzi-Han** [comment]
Any detail logs?

**Comment by Bzi-Han** [comment]
I think you didn't patch this file?

+ ~/../usr/share/cmake-3.26/Modules/Platform/Android/Determine-Compiler.cmake

Or there is a possibility that you patch the wrong file, the path `~/../usr/share/cmake-${version}/Modules/Platform` is CMake scripts path in Termux.
If you didn't find those 5 original files in the CMake scripts path, then you must be patching the wrong path.

**Comment by Bzi-Han** [comment]
Try `rm -rf build`, then build again.

**Comment by Bzi-Han** [comment]
[Termux CMake3.26 patch files for TermuxNDK.zip](https://github.com/Bzi-Han/AndroidSurfaceImgui/files/12544702/Termux.CMake3.26.patch.files.for.TermuxNDK.zip)

Link: https://github.com/Bzi-Han/AndroidSurfaceImgui/files/12544702/Termux.CMake3.26.patch.files.for.TermuxNDK.zip

You must patch failed.
Just download this upload file using `wget` or `curl`.
Then `unzip` the file, modify `+x` permission, and run `PatchCMake3.26.sh`.

**Comment by Bzi-Han** [comment]
Use this NDK: https://github.com/lzhiyong/termux-ndk/releases/download/ndk-r24/android-ndk-r24-aarch64.zip
Try again.
If it fails, I have no idea how to help you.
