### ISSUE TITLE
看了下你的方案，膜拜还能这么实现

### ISSUE THREAD

**Issue by ilcyuan** [Bzi-Han/AndroidSurfaceImgui#21]
大牛膜拜一下，能加个联系方式交流吗，看了下你的方案在安卓14能绘制出来，问题是不能支持触控，因安卓14彻底删掉了不受信任的窗体触摸事件向下传递，设置关闭屏蔽全局不可信任触摸也不行，原因在这里https://github.com/aosp-mirror/platform_frameworks_base/commit/42e5b7014b1aab533d5289c017c8846899fed2d0

**Comment by Bzi-Han** [comment]
QQ2950091819
