### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by lileini** [Bzi-Han/AndroidSurfaceImgui#24]
我在模拟器上运行时报错
![image](https://github.com/user-attachments/assets/83fdbcec-b4a5-4719-b611-d1daf263c763)

**Comment by lileini** [comment]
![image](https://github.com/user-attachments/assets/d5cd8d57-b84d-4a8c-bc89-56469d845e93)

**Comment by lileini** [comment]
找到原因了 模拟器版本不正确

**Comment by Bzi-Han** [comment]
那我关掉issue了
