### ISSUE TITLE
​Add support for Android15

### ISSUE THREAD

**Issue by Nuthon01** [Bzi-Han/AndroidSurfaceImgui#27]
Hello developers, can you add support for Android15.😘😘

**Comment by Bzi-Han** [comment]
Is there any problem with it running on Android 15 devices?

**Comment by Nuthon01** [comment]
打包编译出来的二进制文件都不能正常执行了，Segmentation fault。

**Comment by Bzi-Han** [comment]
更新了

**Comment by Nuthon01** [comment]
I compile the test using the new code you submit, but there is still a Segmentation fault😭😭

**Comment by Nuthon01** [comment]
Thanks for the update, android15 is ready to use.

**Comment by Bzi-Han** [comment]
好，那我关issue了
