### ISSUE TITLE
I have questions

### ISSUE THREAD

**Issue by nyaruru1** [Bzi-Han/AndroidSurfaceImgui#4]
How to build on android phone i want to make surface in android

**Comment by Bzi-Han** [comment]
For build this project you can see [README.md](https://github.com/Bzi-Han/AndroidSurfaceImgui#%E7%BC%96%E8%AF%91), you can use `Termux` app to complete it on Android phone.
Or if you want to use the `Surface` standalone, you can copy the [modules/ANativeWindowCreator.h](https://github.com/Bzi-Han/AndroidSurfaceImgui/blob/main/modules/ANativeWindowCreator.h) header file into your project and include it.
Then you can call [android::ANativeWindowCreator::Create](https://github.com/Bzi-Han/AndroidSurfaceImgui/blob/main/modules/ANativeWindowCreator.h#L268) to create a `Surface`.

**Comment by Bzi-Han** [comment]
I'm tried [termux-ndk-r24](https://github.com/lzhiyong/termux-ndk/releases/tag/ndk-r24), it works well.

But you need patch 5 files of [Android-Clang.cmake, Android-Determine.cmake, Android-Initialize.cmake, Android.cmake, Determine-Compiler.cmake](https://github.com/Lzhiyong/termux-ndk/tree/master/patches/cmake), then the CMake should be work to build.

For me, there files path is:
+ ~/../usr/share/cmake-3.26/Modules/Platform/Android-Clang.cmake
+ ~/../usr/share/cmake-3.26/Modules/Platform/Android-Determine.cmake
+ ~/../usr/share/cmake-3.26/Modules/Platform/Android-Initialize.cmake
+ ~/../usr/share/cmake-3.26/Modules/Platform/Android.cmake
+ ~/../usr/share/cmake-3.26/Modules/Platform/Android/Determine-Compiler.cmake

CMake version is `3.26.4`.

![AndroidPhoneCMakeBuild](https://github.com/Bzi-Han/AndroidSurfaceImgui/assets/75075077/1717a3a4-dfaf-4b97-a55b-d33a2d992407)

**Comment by Bzi-Han** [comment]
Here: https://github.com/Lzhiyong/termux-ndk/tree/master/patches/cmake
